// <auto-generated />
namespace Projekat.Migrations.MaterijalContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dodavanjeRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodavanjeRole));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131240091_dodavanjeRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
